services:
  
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    hostname: invoice-manager-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - linguaPass.backend
    volumes:
      - data.rabbitmq:/var/lib/rabbitmq:rw

  #----------------------------------------------
  
  identity.database:
    image: postgres:latest
    environment:
      POSTGRES_DB: identity
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - identity.database:/var/lib/postgresql/data:rw
    networks:
      - linguaPass.backend
  
  #----------------------------------------------
  
  course.database:
    image: postgres:latest
    environment:
      POSTGRES_DB: course
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - course.database:/var/lib/postgresql/data:rw
    networks:
      - linguaPass.backend
  
  #----------------------------------------------

  account.database:
    image: postgres:latest
    environment:
      POSTGRES_DB: account
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - account.database:/var/lib/postgresql/data:rw
    networks:
      - linguaPass.backend

  #----------------------------------------------
  
  progress.database:
    image: postgres:latest
    environment:
      POSTGRES_DB: progress
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    volumes:
      - progress.database:/var/lib/postgresql/data:rw
    networks:
      - linguaPass.backend

  #----------------------------------------------

volumes:
  data.rabbitmq:
  identity.database:
  course.database:
  account.database:
  progress.database:

networks:
  linguaPass.backend:
    driver: bridge