export { ConfirmBlock } from './ConfirmBlock/ConfirmBlock';
export { ContactForm } from './ContactForm/ContactForm';
export { CourseList } from './CourseList/CourseList';
export { FileUploader } from './FileUploader/FileUploader';
export { LanguageList } from './LanguageList/LanguageList';
export { Menu } from './Menu/Menu';
export { PersonalForm } from './PersonalForm/PersonalForm';
export { ResultBlock } from './ResultBlock/ResultBlock';
export { SchoolList } from './SchoolList/SchoolList';
